/* eslint-disable @typescript-eslint/naming-convention */
// https://unicode.org/emoji/charts/full-emoji-list.html
const icons = {
    sunny: "☀",
    heart: "❤",
    snowflake: "❄",
    checkmark: "✔",
    airplane: "✈",
    envelope: "✉",
    relaxed: "☺",
    hourglass: "⌛",
    scissors: "✂",
    cloud: "☁",
    arrow_forward: "▶",
    four_leaf_clover: "🍀",
    arrow_right: "➡",
    victory: "✌",
    point_up: "☝",
    alarm_clock: "⏰",
    tada: "🎉",
    exclamation: "❗",
    coffee: "☕",
    watch: "⌚",
    football: "🏈",
    fire: "🔥",
    gift: "🎁",
    pizza: "🍕",
    stuck_out_tongue: "😜",
    sunglasses: "😎",
    moneybag: "💰",
    bulb: "💡",
    thumbsup: "👍",
    santa: "🎅",
    christmas_tree: "🎄",
    star: "⭐",
    arrow_up: "⬆",
    question: "❓",
    sparkles: "✨",
    pencil2: "✏",
    raised_hand: "✋",
    zap: "⚡",
    anchor: "⚓",
    umbrella: "☔",
    arrow_backward: "◀",
    hourglass_flowing_sand: "⏳",
    speedboat: "🚤",
    blue_car: "🚙",
    helicopter: "🚁",
    see_no_evil: "🙈",
    key: "🔑",
}

export default icons
